language: c
install:
    - sudo apt-get update
    - sudo apt-get install bc
compiler:
  - gcc
script:
  - make defconfig ARCH=sim && make clean ARCH=sim && make library ARCH=sim
  - ./arch/sim/test/nuse/nuse-test.sh
