language: c
install:
    - sudo apt-get update
    - sudo apt-get install bc
compiler:
  - gcc
# Change this to your needs
script:
  - make defconfig ARCH=sim && make clean ARCH=sim && make library ARCH=sim
  - IFNAME=`ip route |grep default | awk '{print $5}'`
  - GW=`ip route |grep default | awk '{print $3}'`
  # XXX
  - IPADDR=`echo $GW | sed -r "s/([0-9]+\.[0-9]+\.[0-9]+\.)([0-9]+)$/\1`expr \2 + 10`/"`
  - sudo NUSEDEV=eth0 nuse-eth0=${IPADDR} ./nuse ping ${GW} -c 1
#  - make bake -C arch/sim/test && make testbin -C arch/sim/test 
#  - make test ARCH=sim ADD_PARAM="-r"
