language: c
install:
    - sudo apt-get update
    - sudo apt-get install bc
compiler:
  - gcc
script:
  - make defconfig ARCH=lib V=1 && make clean ARCH=lib V=1 && make library ARCH=lib V=1
  - ./arch/lib/test/nuse-test.sh
