language: c
install:
    - sudo apt-get update
    - sudo apt-get install bc
compiler:
  - gcc
# Change this to your needs
script:
  - make defconfig ARCH=sim && make clean ARCH=sim && make library ARCH=sim
  - sudo modprobe tun
  - ls /lib/modules/`uname -r`/kernel/drivers/net/
  - sudo NUSEDEV=tap0 NUSEVIF=TAP nuse-tap0=192.168.0.2 ./nuse sleep 100 &
  - sudo ip addr add 192.168.0.1/24 dev nuse-tap0
  - ping 192.168.0.2 -c 1 | grep ttl
#  - make bake -C arch/sim/test && make testbin -C arch/sim/test 
#  - make test ARCH=sim ADD_PARAM="-r"
